files: ^.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        args:
          [
            --std=c++11,
            --language=c++,
            --enable=all,
            --suppress=unusedFunction,
            --suppress=unmatchedSuppression,
            --suppress=missingIncludeSystem,
            --suppress=toomanyconfigs,
            --error-exitcode=1,
          ]
        files: \.(c|h|cpp)$
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        language: python
        types: [python]
        args: ["--line-length=120"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
