name: build

on:
  push:
    branches: [ "main", "mlpack" ]
  pull_request:
    branches: [ "main", "mlpack" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install pybind11 matplotplusplus boost xtensor eigen mlpack
        cmake --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: mkdir build && cd build && cmake .. && make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
